
# ------------------------------------------------------------------------------
# gestiondeturnos - SonarQube Analysis Configuration
# ------------------------------------------------------------------------------

sonar.projectKey=gestiondeturnos-backend
sonar.projectName=GestionDeTurnos Backend
sonar.projectVersion=1.0.0
sonar.python.version=3.11

# Source code location
sonar.sources=backend/app
sonar.tests=backend/app/tests

# Exclusions
sonar.exclusions=**/__init__.py, **/conftest.py, **/tests/**, **/*.html, **/*.css, **/*.js
sonar.coverage.exclusions=**/__init__.py, **/conftest.py, **/tests/**, **/models/**, **/schemas/**, backend/app/main.py, backend/app/init_auth.py

# Coverage Report
sonar.python.coverage.reportPaths=coverage.xml
sonar.scm.disabled=true
